### ISSUE TITLE
Nu se actualizeaza

### ISSUE THREAD

**Issue by mihneabondor** [Utwo/ctpcj-scraper#10]
Salut,

Folosesc acest repo in aplicatia mea si pare ca de ceva timp datele nu s-au mai actualizat. Cum pot rezolva asta?

**Comment by Utwo** [comment]
Salut,

Am facut trigger acum la un build nou, ar trebui sa ai ultimele date disponibile. 
Github imi permite sa am scheduled workflows doar pentru 60 de zile dupa ultimul commit. Din aceasta cauza datele nu au mai fost actualizate.
