### ISSUE TITLE
Rata pentru update?

### ISSUE THREAD

**Issue by mihneabondor** [Utwo/ctpcj-scraper#9]
Salut,

La ce interval de timp se updateaza datele live? Vad ca au trecut 3 zile de cand s-au schimbat orarele si pe site nimic.

**Comment by Utwo** [comment]
Salut, datele se updateaza o data pe saptamana folosind [Github Actions Cron](https://github.com/Utwo/ctpcj-scraper/blob/master/.github/workflows/cron.yaml). Intr-adevar probabil din cauza ca repo-ul a fost inactiv, nu s-a mai executat CI-ul. 

Am facut acuma un dummy commit, ar trebui ca ultimele date sa fie disponibile.
